export const 
home 			= '/',
join 			= '/join',
login 			= '/login',
forgotPassword 	= '/forgot-password',
resetPassword 	= '/reset-password/:token',
invalid 		= '/invalid',
dashboard 		= '/dashboard',
teacherListing 	= '/teachers',
teacherDetail 	= '/teacher-detail',
addStudent      = '/add-student',
editTeacher 	= '/edit-teacher/:id',
faq 	        = '/faq',
schoolstep 	    = '/school-step',
notFound 		= '*';