export const 
home 			= '/',
join 			= '/join',
login 			= '/login',
forgotPassword 	= '/forgot-password',
resetPassword 	= '/reset-password/:token',
invalid 		= '/invalid',
dashboard 		= '/dashboard',
teacherListing 	= '/teachers',
teacherDetail 	= '/teacher-detail/:id',
studentDetail 	= '/student-detail/:id',
studentListing  = '/students',
editTeacher 	= '/edit-teacher/:id',
editSchoolProfile 	= '/edit-school-profile/:id',
editStudent 	= '/edit-student/:id',
schoolProfile 	= '/school-profile/:id',
AddClass 		= '/add-class',
ClassListing 	= '/classes',
faq 	        = '/help',
schoolstep 	    = '/school-step',
parentlistings 	= '/parents',
notFound 		= '*';

