export const 
home 			= '/',
join 			= '/join',
login 			= '/login',
forgotPassword 	= '/forgot-password',
resetPassword 	= '/reset-password/:token',
invalid 		= '/invalid',
dashboard 		= '/dashboard',
teacherListing 	= '/teachers',
teacherDetail 	= '/teacher-detail/:id',
studentDetail 	= '/student-detail',
addStudent      = '/students',
editTeacher 	= '/edit-teacher/:id',
editStudent 	= '/edit-student',
schoolProfile 	= '/school-profile',
faq 	        = '/faq',
schoolstep 	    = '/school-step',
notFound 		= '*';