version: '2'
services:
  web:
    restart: always
    build: .
    container_name: hoteljot
    ports:
     - "3000:3000"
     - "8080:8080"
    environment:
     - NODE_ENV=development
     - MONGODB_URL=mongodb://hoteljotdb:eGkNCtz4cy8a6XNj0a5smQSPwzCpnroiIrOqru4EWaQe1XnQv67UWkQMgwsbiwVBnc6uFcfMMB7ikMyPAdSVXw==@hoteljotdb.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
    volumes_from:
     - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
     - ./:/opt/hoteljot
     - /opt/hoteljot/node_modules
     - /opt/hoteljot/public
     - /opt/hoteljot/uploads
    entrypoint: /bin/true